### PR TITLE
Update for the dev release of Csv import.

### PR DESCRIPTION
**Pull request by Daniel-KM**
https://github.com/omeka-s-modules/CSVImport/pull/105

### CODE REVIEW

**Comment by oupala** [comment]
Please accept this merge request as it should allow to import tags as well as contents.

**Comment by oupala** [comment]
Will this pull request be merged?

I'm hardly waiting for this so that it will be possible to importe sideloaded media and tags.

Please give us status on what you plan to do.

**Comment by zerocrates** [comment]
This won't be merged until the updated CSV Import module itself is released, since these changes are incompatible with the current importer.

It's worth noting that you can already import sideload files with the current released versions of CSV Import and FileSideload.

**Comment by oupala** [comment]
Ok, I understand that this pull request is linked with pull request [CSVImport #105](/omeka-s-modules/CSVImport/pull/105).

And yes, you're right, it's already possible to import media file with the current CVSImport and FileSideLoad.

**Comment by zerocrates** [comment]
Done for 1.2.0.

**Comment by oupala** [comment]
Great news! Thanks @Daniel-KM and @zerocrates

**Pull request closed without merging**
